// skills/interactive-showcase-site/templates/explainer/src/components/Tabs.tsx
/**
 * Tabs — variant-style switcher. Props-only API: each tab's body is a raw HTML
 * string (author-provided, trusted in this skill's context) injected via
 * dangerouslySetInnerHTML. Styles: src/styles/components/tabs.css.
 */
import { useState } from 'react';
import type { KeyboardEvent } from 'react';

type Tab = { label: string; html: string };
type Props = {
  tabs: Tab[];
  group?: string;
  initial?: number;
};

export default function Tabs({ tabs, group = 'tabs', initial = 0 }: Props) {
  const [active, setActive] = useState(initial);

  function selectByKey(event: KeyboardEvent<HTMLButtonElement>, idx: number) {
    if (event.key === 'ArrowRight') {
      event.preventDefault();
      setActive((idx + 1) % tabs.length);
    } else if (event.key === 'ArrowLeft') {
      event.preventDefault();
      setActive((idx - 1 + tabs.length) % tabs.length);
    } else if (event.key === 'Home') {
      event.preventDefault();
      setActive(0);
    } else if (event.key === 'End') {
      event.preventDefault();
      setActive(tabs.length - 1);
    }
  }

  return (
    <div className="tabs-wrap">
      <div role="tablist" className="tablist" aria-label={group}>
        {tabs.map((tab, i) => (
          <button
            key={tab.label}
            role="tab"
            id={`tab-${group}-${i}`}
            aria-selected={active === i}
            aria-controls={`panel-${group}-${i}`}
            tabIndex={active === i ? 0 : -1}
            className={active === i ? 'tab active' : 'tab'}
            onClick={() => setActive(i)}
            onKeyDown={(e) => selectByKey(e, i)}
          >
            {tab.label}
          </button>
        ))}
      </div>
      {tabs.map((tab, i) => (
        <div
          key={tab.label}
          role="tabpanel"
          id={`panel-${group}-${i}`}
          aria-labelledby={`tab-${group}-${i}`}
          hidden={active !== i}
          className="panel"
          dangerouslySetInnerHTML={{ __html: tab.html }}
        />
      ))}
    </div>
  );
}

// skills/interactive-showcase-site/template/src/components/Tabs.svelte
<script lang="ts">
  /**
   * Tabs — variant-style switcher.
   *
   * Props-only API: no children-as-island (which is unstable across the
   * Astro/Svelte hydration edge). Each tab's body is provided as a raw
   * HTML string in the `tabs` array. For richer content, prefer authoring
   * multiple sections instead of stuffing complex markup into a tab.
   *
   * See SKILL.md "Pattern C" for the authoring contract.
   */
  type Tab = { label: string; html: string };
  type Props = {
    tabs: Tab[];
    group?: string;
    initial?: number;
  };
  let { tabs, group = 'tabs', initial = 0 }: Props = $props();

  let active = $state(initial);

  function selectByKey(e: KeyboardEvent, idx: number) {
    if (e.key === 'ArrowRight') {
      e.preventDefault();
      active = (idx + 1) % tabs.length;
    } else if (e.key === 'ArrowLeft') {
      e.preventDefault();
      active = (idx - 1 + tabs.length) % tabs.length;
    } else if (e.key === 'Home') {
      e.preventDefault();
      active = 0;
    } else if (e.key === 'End') {
      e.preventDefault();
      active = tabs.length - 1;
    }
  }
</script>

<div class="tabs-wrap">
  <div role="tablist" class="tablist" aria-label={group}>
    {#each tabs as tab, i (tab.label)}
      <button
        role="tab"
        id={`tab-${group}-${i}`}
        aria-selected={active === i}
        aria-controls={`panel-${group}-${i}`}
        tabindex={active === i ? 0 : -1}
        class="tab"
        class:active={active === i}
        onclick={() => (active = i)}
        onkeydown={(e) => selectByKey(e, i)}
      >{tab.label}</button>
    {/each}
  </div>
  {#each tabs as tab, i (tab.label)}
    <div
      role="tabpanel"
      id={`panel-${group}-${i}`}
      aria-labelledby={`tab-${group}-${i}`}
      hidden={active !== i}
      class="panel"
    >
      <!-- HTML is author-provided and trusted in this skill's context -->
      <!-- eslint-disable-next-line svelte/no-at-html-tags -->
      {@html tab.html}
    </div>
  {/each}
</div>

<style>
  .tabs-wrap {
    border: 1.5px solid var(--gray-300);
    border-radius: var(--radius-panel);
    overflow: hidden;
    background: var(--paper);
  }
  .tablist {
    display: flex;
    flex-wrap: wrap;
    gap: 0;
    background: var(--gray-100);
    border-bottom: 1px solid var(--gray-300);
    padding: 4px;
  }
  .tab {
    flex: 1 1 auto;
    min-width: 0;
    padding: 8px 14px;
    border: 1.5px solid transparent;
    border-radius: 8px;
    background: transparent;
    color: var(--gray-700);
    font-family: var(--sans);
    font-size: 13.5px;
    font-weight: 500;
    transition: background 0.15s ease, border-color 0.15s ease, color 0.15s ease;
  }
  .tab:hover {
    background: var(--paper);
    border-color: var(--gray-300);
  }
  .tab.active {
    background: var(--paper);
    border-color: var(--clay);
    color: var(--slate);
  }
  .panel {
    padding: 18px 20px;
  }
  .panel > :global(p):first-child { margin-top: 0; }
  .panel > :global(p):last-child  { margin-bottom: 0; }

  @media (max-width: 600px) {
    .tab { flex-basis: 100%; }
  }
</style>
