// skills/interactive-showcase-site/templates/explainer/src/components/Hero.svelte
<script lang="ts">
  /**
   * Hero — page-level hero (eyebrow + h1 + lead + chips + optional first-screen map).
   * NOT the per-section hero. The per-section hero is whatever interactive
   * island (Lifecycle / Mermaid / Tabs / plain prose) the section's MDX places
   * at the top of its body.
   *
   * Used once at the top of index.astro to introduce the whole site.
   *
   * The optional `summaryItems` render as an editorial first-screen map: a
   * full-width hairline-separated list under the title block. No panel, no
   * card grid — typography + 1px gray-300 separators only. Tone is collapsed
   * to a 7px dot at the start of each row.
   */
  type Tone = 'clay' | 'olive' | 'rust' | 'info' | 'muted';
  type Chip = { label: string; tone?: Tone };
  type SummaryItem = {
    label: string;
    title: string;
    body: string;
    tone?: Tone;
  };
  type Props = {
    eyebrow?: string;
    title: string;
    lead?: string;
    chips?: Chip[];
    summaryTitle?: string;
    summaryItems?: SummaryItem[];
  };
  let {
    eyebrow,
    title,
    lead,
    chips = [],
    summaryTitle = 'PROJECT SNAPSHOT',
    summaryItems = []
  }: Props = $props();
</script>

<header class="page-hero" id="top">
  <div class="hero-copy">
    {#if eyebrow}<div class="eyebrow">{eyebrow}</div>{/if}
    <h1 class="title">{title}</h1>
    {#if lead}<p class="lead">{lead}</p>{/if}
    {#if chips.length}
      <div class="chips">
        {#each chips as c (c.label)}
          <span class="chip" data-tone={c.tone ?? 'muted'}>
            <span class="dot" data-tone={c.tone ?? 'muted'}></span>
            {c.label}
          </span>
        {/each}
      </div>
    {/if}
  </div>

  {#if summaryItems.length}
    <section class="summary" aria-label={summaryTitle}>
      <div class="summary-title mono">{summaryTitle}</div>
      <ol class="map-list">
        {#each summaryItems as item (item.label)}
          <li class="map-row">
            <div class="map-num mono">
              <span class="dot" data-tone={item.tone ?? 'muted'}></span>
              {item.label}
            </div>
            <h2 class="map-title">{item.title}</h2>
            <p class="map-body">{item.body}</p>
          </li>
        {/each}
      </ol>
    </section>
  {/if}
</header>

<!-- Styles: src/styles/components/hero.css (aggregated by site.css). -->

// skills/interactive-showcase-site/templates/explainer/src/components/Hero.tsx
/**
 * Hero — page-level hero (eyebrow + h1 + lead + chips + optional first-screen
 * map). Static: no state, no client:* directive, ships zero JS. Styles:
 * src/styles/components/hero.css.
 */
type Tone = 'clay' | 'olive' | 'rust' | 'info' | 'muted';
type Chip = { label: string; tone?: Tone };
type SummaryItem = { label: string; title: string; body: string; tone?: Tone };
type Props = {
  eyebrow?: string;
  title: string;
  lead?: string;
  chips?: Chip[];
  summaryTitle?: string;
  summaryItems?: SummaryItem[];
};

export default function Hero({
  eyebrow,
  title,
  lead,
  chips = [],
  summaryTitle = 'PROJECT SNAPSHOT',
  summaryItems = []
}: Props) {
  return (
    <header className="page-hero" id="top">
      <div className="hero-copy">
        {eyebrow && <div className="eyebrow">{eyebrow}</div>}
        <h1 className="title">{title}</h1>
        {lead && <p className="lead">{lead}</p>}
        {chips.length > 0 && (
          <div className="chips">
            {chips.map((c) => (
              <span key={c.label} className="chip" data-tone={c.tone ?? 'muted'}>
                <span className="dot" data-tone={c.tone ?? 'muted'} />
                {c.label}
              </span>
            ))}
          </div>
        )}
      </div>

      {summaryItems.length > 0 && (
        <section className="summary" aria-label={summaryTitle}>
          <div className="summary-title mono">{summaryTitle}</div>
          <ol className="map-list">
            {summaryItems.map((item) => (
              <li key={item.label} className="map-row">
                <div className="map-num mono">
                  <span className="dot" data-tone={item.tone ?? 'muted'} />
                  {item.label}
                </div>
                <h2 className="map-title">{item.title}</h2>
                <p className="map-body">{item.body}</p>
              </li>
            ))}
          </ol>
        </section>
      )}
    </header>
  );
}
